"""Initial migration

Revision ID: 1351f916bf1e
Revises: 
Create Date: 2025-03-31 19:44:39.801286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1351f916bf1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SEC', 'SG', 'CD', 'ADM', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('EXAMEN', 'COLOCVIU', name='examtype'), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_ASTEPTARE', 'ACCEPTAT', 'RESPINS', name='examstatus'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    op.drop_table('groups')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
