"""added facultyShortName to course model

Revision ID: 21fbfcedcd43
Revises: df98071055b5
Create Date: 2025-04-03 18:59:53.130733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fbfcedcd43'
down_revision = 'df98071055b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facultyShortName', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('facultyShortName')

    # ### end Alembic commands ###
