"""Add Flask-Login support

Revision ID: 2bbafeb89604
Revises: efc0ec77b65e
Create Date: 2025-04-01 19:32:15.974878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbafeb89604'
down_revision = 'efc0ec77b65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assistant_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assistant_id')

    # ### end Alembic commands ###
