"""Added building field for room tables

Revision ID: 307b131cd19c
Revises: 1351f916bf1e
Create Date: 2025-03-31 20:40:50.842912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307b131cd19c'
down_revision = '1351f916bf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('building')

    # ### end Alembic commands ###
