"""Added some fields for course and room

Revision ID: 7195e18c0c40
Revises: 2bbafeb89604
Create Date: 2025-04-02 16:58:15.133179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7195e18c0c40'
down_revision = '2bbafeb89604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studyYear', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('specialization', sa.String(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacherId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('groupName', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('groupName')
        batch_op.drop_column('teacherId')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('specialization')
        batch_op.drop_column('studyYear')

    # ### end Alembic commands ###
