"""year and specialization can be null

Revision ID: df98071055b5
Revises: 7195e18c0c40
Create Date: 2025-04-02 17:32:36.207256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df98071055b5'
down_revision = '7195e18c0c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('studyYear',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('studyYear',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
