"""added assistants to course

Revision ID: efc0ec77b65e
Revises: 307b131cd19c
Create Date: 2025-03-31 22:20:14.101634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc0ec77b65e'
down_revision = '307b131cd19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_assistants',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'assistant_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('courses_professor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['coordinator_id'], ['user_id'])
        batch_op.drop_column('professor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('courses_professor_id_fkey', 'users', ['professor_id'], ['user_id'])
        batch_op.drop_column('coordinator_id')

    op.drop_table('course_assistants')
    # ### end Alembic commands ###
